/* The following code was generated by JFlex 1.6.1 */

/*
	* This is the lexer for compiler by using Jflex
	* And it will be good used by Jcup
	
	to Create the lexer.java
	> jflex lexer.flex
*/
/* --------------------------Usercode Section------------------------ */
import java_cup.runtime.*;
import java.io.*;
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lexer.flex</tt>
 */
class lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\54\1\17"+
    "\1\6\1\7\1\44\1\51\1\15\1\55\1\56\1\5\1\45\1\60"+
    "\1\46\1\66\1\4\1\11\7\12\2\10\1\0\1\57\1\47\1\43"+
    "\1\50\2\0\6\14\21\7\1\13\2\7\1\63\1\16\1\64\1\52"+
    "\1\7\1\0\1\26\1\40\1\24\1\23\1\35\1\34\1\7\1\25"+
    "\1\22\1\7\1\41\1\36\1\7\1\30\1\21\2\7\1\27\1\32"+
    "\1\31\1\33\1\20\1\37\1\13\1\7\1\42\1\61\1\53\1\62"+
    "\1\65\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\1\5\2\6"+
    "\2\1\12\5\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\2\0\1\33"+
    "\1\34\1\6\5\0\1\35\2\5\1\36\12\5\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\0\1\6\2\60\1\35\1\5\1\61\6\5\1\62"+
    "\3\5\1\63\1\64\1\65\1\5\1\66\4\5\1\67"+
    "\6\5\1\70\1\71\1\72\1\5\1\73\1\74\1\75"+
    "\1\5\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\334\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba"+
    "\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b\0\u0672"+
    "\0\67\0\67\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\u0113\0\u06a9\0\67\0\67\0\u06e0\0\u0717"+
    "\0\u074e\0\u0785\0\u0226\0\u07bc\0\67\0\u07f3\0\u082a\0\u014a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2"+
    "\0\u0a19\0\u0a50\0\67\0\67\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\u0a87\0\67\0\u0abe\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\u0af5\0\u0717\0\67\0\u074e\0\u0226"+
    "\0\u0b2c\0\u014a\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76"+
    "\0\u014a\0\u0cad\0\u0ce4\0\u0d1b\0\67\0\67\0\u014a\0\u0d52"+
    "\0\u014a\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u014a\0\u0e65\0\u0e9c"+
    "\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u014a\0\u014a\0\u014a\0\u0faf"+
    "\0\u014a\0\u014a\0\u014a\0\u0fe6\0\u014a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\11\2\10\1\13\1\2\1\14\1\15\1\10"+
    "\1\16\1\10\1\17\2\10\1\20\2\10\1\21\1\22"+
    "\1\23\1\24\1\10\1\25\1\26\2\10\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\71\0\1\4\70\0\1\53\1\54\35\0"+
    "\1\55\66\0\1\56\23\0\2\53\1\4\64\53\7\0"+
    "\6\10\3\0\23\10\34\0\3\11\65\0\2\57\1\60"+
    "\53\0\2\61\1\0\12\61\1\0\1\62\50\61\1\63"+
    "\2\0\13\63\1\64\1\65\47\63\7\0\6\10\3\0"+
    "\1\10\1\66\21\10\33\0\6\10\3\0\10\10\1\67"+
    "\3\10\1\70\6\10\33\0\6\10\3\0\1\10\1\71"+
    "\3\10\1\72\15\10\33\0\6\10\3\0\15\10\1\73"+
    "\5\10\33\0\6\10\3\0\2\10\1\74\6\10\1\75"+
    "\11\10\33\0\6\10\3\0\10\10\1\76\12\10\33\0"+
    "\6\10\3\0\1\10\1\77\21\10\33\0\6\10\3\0"+
    "\16\10\1\100\4\10\33\0\6\10\3\0\5\10\1\101"+
    "\15\10\33\0\6\10\3\0\7\10\1\102\13\10\67\0"+
    "\1\103\66\0\1\104\66\0\1\105\1\0\1\106\64\0"+
    "\1\107\2\0\1\110\1\0\1\111\61\0\1\112\3\0"+
    "\1\113\62\0\1\114\4\0\1\115\61\0\1\116\5\0"+
    "\1\117\60\0\1\120\66\0\1\121\7\0\1\122\56\0"+
    "\1\123\23\0\4\54\1\0\1\124\61\54\11\0\2\57"+
    "\64\0\3\125\1\0\1\125\6\0\2\125\1\0\1\125"+
    "\5\0\2\125\2\0\1\125\26\0\2\61\1\0\12\61"+
    "\1\126\1\62\52\61\1\0\12\61\1\127\1\62\50\61"+
    "\1\63\2\0\13\63\1\64\1\130\47\63\7\0\6\10"+
    "\3\0\2\10\1\131\20\10\33\0\6\10\3\0\11\10"+
    "\1\132\11\10\33\0\6\10\3\0\10\10\1\133\12\10"+
    "\33\0\6\10\3\0\6\10\1\134\14\10\33\0\6\10"+
    "\3\0\11\10\1\135\11\10\33\0\6\10\3\0\22\10"+
    "\1\136\33\0\6\10\3\0\7\10\1\137\13\10\33\0"+
    "\6\10\3\0\2\10\1\140\20\10\33\0\6\10\3\0"+
    "\7\10\1\141\13\10\33\0\6\10\3\0\12\10\1\142"+
    "\10\10\33\0\6\10\3\0\2\10\1\143\20\10\33\0"+
    "\6\10\3\0\15\10\1\144\5\10\67\0\1\145\66\0"+
    "\1\146\27\0\1\4\71\0\6\10\3\0\3\10\1\147"+
    "\17\10\33\0\6\10\3\0\11\10\1\150\11\10\33\0"+
    "\6\10\3\0\7\10\1\151\13\10\33\0\6\10\3\0"+
    "\13\10\1\152\7\10\33\0\6\10\3\0\15\10\1\153"+
    "\5\10\33\0\6\10\3\0\13\10\1\154\7\10\33\0"+
    "\6\10\3\0\1\10\1\155\21\10\33\0\6\10\3\0"+
    "\15\10\1\156\5\10\33\0\6\10\3\0\16\10\1\157"+
    "\4\10\33\0\6\10\3\0\6\10\1\160\14\10\33\0"+
    "\6\10\3\0\2\10\1\161\20\10\33\0\6\10\3\0"+
    "\7\10\1\162\13\10\33\0\6\10\3\0\1\10\1\163"+
    "\21\10\33\0\6\10\3\0\4\10\1\164\16\10\33\0"+
    "\6\10\3\0\10\10\1\165\12\10\33\0\6\10\3\0"+
    "\15\10\1\166\5\10\33\0\6\10\3\0\21\10\1\167"+
    "\1\10\33\0\6\10\3\0\10\10\1\170\12\10\33\0"+
    "\6\10\3\0\10\10\1\171\12\10\33\0\6\10\3\0"+
    "\14\10\1\172\6\10\33\0\6\10\3\0\11\10\1\173"+
    "\11\10\33\0\6\10\3\0\13\10\1\174\7\10\33\0"+
    "\6\10\3\0\15\10\1\175\5\10\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4125];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\34\1\12\11\2\0\2\11"+
    "\1\1\5\0\1\11\15\1\10\11\1\1\1\11\1\1"+
    "\6\11\1\0\1\1\1\11\16\1\2\11\27\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

	StringBuffer string = new StringBuffer();
	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character<"+yytext()+">");
            }
          case 63: break;
          case 2: 
            { /*ignore*/
            }
          case 64: break;
          case 3: 
            { return symbol(sym.DIV);
            }
          case 65: break;
          case 4: 
            { return symbol(sym.MUL);
            }
          case 66: break;
          case 5: 
            { return symbol(sym.ID, yytext());
            }
          case 67: break;
          case 6: 
            { return symbol(sym.CONSTINT, yytext());
            }
          case 68: break;
          case 7: 
            { return symbol(sym.EVA);
            }
          case 69: break;
          case 8: 
            { return symbol(sym.MOD);
            }
          case 70: break;
          case 9: 
            { return symbol(sym.ADD);
            }
          case 71: break;
          case 10: 
            { return symbol(sym.SUB);
            }
          case 72: break;
          case 11: 
            { return symbol(sym.LT);
            }
          case 73: break;
          case 12: 
            { return symbol(sym.GT);
            }
          case 74: break;
          case 13: 
            { return symbol(sym.AND);
            }
          case 75: break;
          case 14: 
            { return symbol(sym.XOR);
            }
          case 76: break;
          case 15: 
            { return symbol(sym.OR);
            }
          case 77: break;
          case 16: 
            { return symbol(sym.NOT);
            }
          case 78: break;
          case 17: 
            { return symbol(sym.LPA);
            }
          case 79: break;
          case 18: 
            { return symbol(sym.RPA);
            }
          case 80: break;
          case 19: 
            { return symbol(sym.SEMI);
            }
          case 81: break;
          case 20: 
            { return symbol(sym.COMMA);
            }
          case 82: break;
          case 21: 
            { return symbol(sym.LCU);
            }
          case 83: break;
          case 22: 
            { return symbol(sym.RCU);
            }
          case 84: break;
          case 23: 
            { return symbol(sym.LSQ);
            }
          case 85: break;
          case 24: 
            { return symbol(sym.RSQ);
            }
          case 86: break;
          case 25: 
            { return symbol(sym.COM);
            }
          case 87: break;
          case 26: 
            { return symbol(sym.DOT);
            }
          case 88: break;
          case 27: 
            { return symbol(sym.DIV_ASSIGN);
            }
          case 89: break;
          case 28: 
            { return symbol(sym.MUL_ASSIGN);
            }
          case 90: break;
          case 29: 
            { return symbol(sym.CONSTSTR, yytext());
            }
          case 91: break;
          case 30: 
            { return symbol(sym.IF);
            }
          case 92: break;
          case 31: 
            { return symbol(sym.EQ);
            }
          case 93: break;
          case 32: 
            { return symbol(sym.MOD_ASSIGN);
            }
          case 94: break;
          case 33: 
            { return symbol(sym.ADD_ASSIGN);
            }
          case 95: break;
          case 34: 
            { return symbol(sym.INC);
            }
          case 96: break;
          case 35: 
            { return symbol(sym.SUB_ASSIGN);
            }
          case 97: break;
          case 36: 
            { return symbol(sym.DEC);
            }
          case 98: break;
          case 37: 
            { return symbol(sym.PTR);
            }
          case 99: break;
          case 38: 
            { return symbol(sym.LE);
            }
          case 100: break;
          case 39: 
            { return symbol(sym.SHL);
            }
          case 101: break;
          case 40: 
            { return symbol(sym.GE);
            }
          case 102: break;
          case 41: 
            { return symbol(sym.SHR);
            }
          case 103: break;
          case 42: 
            { return symbol(sym.AND_ASSIGN);
            }
          case 104: break;
          case 43: 
            { return symbol(sym.AND_L);
            }
          case 105: break;
          case 44: 
            { return symbol(sym.XOR_ASSIGN);
            }
          case 106: break;
          case 45: 
            { return symbol(sym.OR_ASSIGN);
            }
          case 107: break;
          case 46: 
            { return symbol(sym.OR_L);
            }
          case 108: break;
          case 47: 
            { return symbol(sym.NE);
            }
          case 109: break;
          case 48: 
            { return symbol(sym.CONSTCHAR, yytext());
            }
          case 110: break;
          case 49: 
            { return symbol(sym.INT);
            }
          case 111: break;
          case 50: 
            { return symbol(sym.FOR);
            }
          case 112: break;
          case 51: 
            { return symbol(sym.SHL_ASSIGN);
            }
          case 113: break;
          case 52: 
            { return symbol(sym.SHR_ASSIGN);
            }
          case 114: break;
          case 53: 
            { return symbol(sym.VOID);
            }
          case 115: break;
          case 54: 
            { return symbol(sym.CHAR);
            }
          case 116: break;
          case 55: 
            { return symbol(sym.ELSE);
            }
          case 117: break;
          case 56: 
            { return symbol(sym.UNION);
            }
          case 118: break;
          case 57: 
            { return symbol(sym.WHILE);
            }
          case 119: break;
          case 58: 
            { return symbol(sym.BREAK);
            }
          case 120: break;
          case 59: 
            { return symbol(sym.RETURN);
            }
          case 121: break;
          case 60: 
            { return symbol(sym.SIZEOF);
            }
          case 122: break;
          case 61: 
            { return symbol(sym.STRUCT);
            }
          case 123: break;
          case 62: 
            { return symbol(sym.CONTINUE);
            }
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
