
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHR_ASSIGN = 54;
  public static final int SHR = 44;
  public static final int XOR_ASSIGN = 56;
  public static final int SHL = 43;
  public static final int CHAR = 3;
  public static final int GE = 42;
  public static final int OR_L = 37;
  public static final int XOR = 26;
  public static final int SEMI = 17;
  public static final int CONTINUE = 11;
  public static final int INT = 4;
  public static final int FOR = 10;
  public static final int LSQ = 22;
  public static final int EVA = 19;
  public static final int SUB_ASSIGN = 52;
  public static final int NOT = 35;
  public static final int SIZEOF = 14;
  public static final int AND = 27;
  public static final int LT = 28;
  public static final int OR = 25;
  public static final int COMMA = 18;
  public static final int INC = 45;
  public static final int DIV = 32;
  public static final int LPA = 15;
  public static final int IF = 7;
  public static final int LCU = 20;
  public static final int ID = 58;
  public static final int PTR = 47;
  public static final int DOT = 36;
  public static final int LE = 41;
  public static final int ADD_ASSIGN = 51;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 53;
  public static final int MUL = 24;
  public static final int AND_L = 38;
  public static final int RSQ = 23;
  public static final int ADD = 30;
  public static final int CONSTSTR = 61;
  public static final int MOD = 33;
  public static final int BREAK = 12;
  public static final int VOID = 2;
  public static final int EQ = 39;
  public static final int MOD_ASSIGN = 50;
  public static final int DIV_ASSIGN = 49;
  public static final int COM = 34;
  public static final int CONSTINT = 59;
  public static final int UNION = 6;
  public static final int RPA = 16;
  public static final int ELSE = 8;
  public static final int AND_ASSIGN = 55;
  public static final int RCU = 21;
  public static final int WHILE = 9;
  public static final int OR_ASSIGN = 57;
  public static final int NE = 40;
  public static final int MUL_ASSIGN = 48;
  public static final int CONSTCHAR = 60;
  public static final int DEC = 46;
  public static final int STRUCT = 5;
  public static final int GT = 29;
  public static final int SUB = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "CHAR",
  "INT",
  "STRUCT",
  "UNION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "CONTINUE",
  "BREAK",
  "RETURN",
  "SIZEOF",
  "LPA",
  "RPA",
  "SEMI",
  "COMMA",
  "EVA",
  "LCU",
  "RCU",
  "LSQ",
  "RSQ",
  "MUL",
  "OR",
  "XOR",
  "AND",
  "LT",
  "GT",
  "ADD",
  "SUB",
  "DIV",
  "MOD",
  "COM",
  "NOT",
  "DOT",
  "OR_L",
  "AND_L",
  "EQ",
  "NE",
  "LE",
  "GE",
  "SHL",
  "SHR",
  "INC",
  "DEC",
  "PTR",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "SHL_ASSIGN",
  "SHR_ASSIGN",
  "AND_ASSIGN",
  "XOR_ASSIGN",
  "OR_ASSIGN",
  "ID",
  "CONSTINT",
  "CONSTCHAR",
  "CONSTSTR"
  };
}

